{% set version = "0.10.0" %}

package:
  name: requests-toolbelt
  version: {{ version }}

source:
  fn: requests-toolbelt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/requests-toolbelt/requests-toolbelt-{{ version }}.tar.gz
  sha256: f695d6207931200b46c8ef6addbc8a921fb5d77cc4cd209c2e7d39293fcd2b30

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - requests >=2.0.1,<=3.0.0

test:
  imports:
    - requests_toolbelt
    - requests_toolbelt.adapters
    - requests_toolbelt.auth
    - requests_toolbelt.downloadutils
    - requests_toolbelt.multipart
    - requests_toolbelt.threaded
    - requests_toolbelt.utils

about:
  home: https://toolbelt.readthedocs.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A utility belt for advanced users of python-requests.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - sigmavirus24
